<?xml version="1.0"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="common_properties.xacro" />
    <xacro:include filename="mobile_base.xacro" />
    <xacro:include filename="mobile_base_gazebo.xacro" />
    <xacro:include filename="camera.xacro" />
    <xacro:include filename="lidar.xacro" />
    <!-- <xacro:include filename="arm_mobile_base.xacro" />
    <xacro:include filename="arm_gazebo.xacro" /> -->

    <!-- <joint name="robot_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_footprint" />
        <origin xyz="-0.1 0 ${base_height}" rpy="0 0 0" />
    </joint> -->

    <joint name="lidar_base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${base_height+lidar_length/2}" rpy="0 0 0" />
    </joint>


</robot>